### ISSUE TITLE
Dataset Selection

### ISSUE THREAD

**Issue by EnisBerk** [Yunhua468/Audio-Visual-Emotion-and-Sentiment-Research#1]
Let's discuss the dataset here.

**Comment by Yunhua468** [comment]
Hi guys,

How about have a short talk about this project? We could discuss how to divide the dataset and task assign, thank you.

**Comment by Yunhua468** [comment]
Hello guys,

Let us have a short discuss about the mission and next step, Patrick Jean-Baptiste is ok after 1pm, so how about 2pm?

**Comment by EnisBerk** [comment]
We agreed to work on [RAVDESS dataset ](https://zenodo.org/record/1188976#.XqN9yG5Fw2x)
[wiki](https://github.com/Yunhua468/Audio-Visual-Emotion-and-Sentiment-Research/blob/master/Documents/Viki-Doc.txt)
