### ISSUE TITLE
Accessing Dataset is slow

### ISSUE THREAD

**Issue by EnisBerk** [Yunhua468/Audio-Visual-Emotion-and-Sentiment-Research#2]
Dataset is 25Gb in total and it is slow to download from Zenodo.To be able to use Colab or other cloud offerings, we can upload it to somewhere. Are you working locally or do you have a copy on the cloud?

**Comment by Yunhua468** [comment]
Hi Enis, I work locally

**Comment by patrick-jean-baptiste** [comment]
Hi, I work locally as well. I am only processing part of the dataset at a time.

**Comment by EnisBerk** [comment]
Sounds good, here is what I am using to download the data if anybody needs to use Collab in the future:
```python3
import requests
r = requests.get('https://zenodo.org/api/records/1188976')
with open("download.txt", "w+") as f:
    for file in r.json()["files"]:
        aLink=(file["links"]["self"])
        f.write(aLink+"\n")

!sudo apt-get install -y aria2
!aria2c -i download.txt -d ./dataset
!unzip "/content/SharedDatasets/dataset/*" -d ./unzipped/
```
